export const PERMISSIONS = {
  VIEW_EMPLOYEES: 'view_employees',
  ADD_EMPLOYEE: 'add_employee',
  EDIT_EMPLOYEE: 'edit_employee',
  DELETE_EMPLOYEE: 'delete_employee',
  APPLY_LEAVE: 'apply_leave',
  VIEW_LEAVES: 'view_leaves',
  ASSIGN_TASK: 'assign_task',
  APPROVE_LEAVE: 'approve_leave',
  VIEW_ANALYTICS: 'view_analytics',
  VIEW_TEAM_ATTENDANCE: 'view_team_attendance',
  VIEW_PAYROLL: 'view_payroll',
  MANAGE_PAYROLL: 'manage_payroll',
}

export const ROLE_PERMISSIONS = {
  super_admin: Object.values(PERMISSIONS),
  hr_manager: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.ADD_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.DELETE_EMPLOYEE,
    PERMISSIONS.APPLY_LEAVE,
    PERMISSIONS.VIEW_LEAVES,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.APPROVE_LEAVE,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_TEAM_ATTENDANCE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.MANAGE_PAYROLL,
  ],
  department_manager: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.ADD_EMPLOYEE,
    PERMISSIONS.EDIT_EMPLOYEE,
    PERMISSIONS.APPLY_LEAVE,
    PERMISSIONS.VIEW_LEAVES,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.APPROVE_LEAVE,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_TEAM_ATTENDANCE,
    PERMISSIONS.VIEW_PAYROLL,
    PERMISSIONS.MANAGE_PAYROLL,
  ],
  employee: [PERMISSIONS.VIEW_EMPLOYEES, PERMISSIONS.APPLY_LEAVE, PERMISSIONS.VIEW_LEAVES],
  recruiter: [PERMISSIONS.ADD_EMPLOYEE, PERMISSIONS.EDIT_EMPLOYEE],
  institute_admin: Object.values(PERMISSIONS),
  faculty: [
    PERMISSIONS.VIEW_EMPLOYEES,
    PERMISSIONS.APPLY_LEAVE,
    PERMISSIONS.VIEW_LEAVES,
    PERMISSIONS.ASSIGN_TASK,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  student: [PERMISSIONS.APPLY_LEAVE, PERMISSIONS.VIEW_LEAVES],
  placement_officer: [PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.ASSIGN_TASK],
}

export const hasPermission = (role, permission) => {
  return Boolean(ROLE_PERMISSIONS[role]?.includes(permission))
}
