export const employees = [
  {
    id: 'EMP-1024',
    name: 'Avery Reed',
    role: 'HR Admin',
    department: 'People Ops',
    location: 'New York, US',
    status: 'Active',
    email: 'avery.reed@workpulse.com',
    phone: '+1 646 555 0142',
    manager: 'Jordan Patel',
    startDate: 'Feb 01, 2021',
    attendance: '97%',
    productivity: '88',
  },
  {
    id: 'EMP-1088',
    name: 'Jordan Patel',
    role: 'Engineering Manager',
    department: 'Engineering',
    location: 'Austin, US',
    status: 'Active',
    email: 'jordan.patel@workpulse.com',
    phone: '+1 512 555 0089',
    manager: 'Nia Carter',
    startDate: 'May 14, 2019',
    attendance: '95%',
    productivity: '91',
  },
  {
    id: 'EMP-1102',
    name: 'Nia Carter',
    role: 'VP Operations',
    department: 'Operations',
    location: 'London, UK',
    status: 'Active',
    email: 'nia.carter@workpulse.com',
    phone: '+44 20 7946 0123',
    manager: '—',
    startDate: 'Sep 21, 2018',
    attendance: '98%',
    productivity: '94',
  },
  {
    id: 'EMP-1156',
    name: 'Liam Chen',
    role: 'Product Designer',
    department: 'Design',
    location: 'Singapore',
    status: 'On Leave',
    email: 'liam.chen@workpulse.com',
    phone: '+65 6123 8901',
    manager: 'Jordan Patel',
    startDate: 'Nov 12, 2022',
    attendance: '92%',
    productivity: '85',
  },
  {
    id: 'EMP-1189',
    name: 'Noah Brooks',
    role: 'Finance Analyst',
    department: 'Finance',
    location: 'Toronto, CA',
    status: 'Active',
    email: 'noah.brooks@workpulse.com',
    phone: '+1 416 555 0177',
    manager: 'Nia Carter',
    startDate: 'Aug 08, 2021',
    attendance: '96%',
    productivity: '90',
  },
  {
    id: 'EMP-1213',
    name: 'Sofia Alvarez',
    role: 'People Partner',
    department: 'People Ops',
    location: 'Madrid, ES',
    status: 'Inactive',
    email: 'sofia.alvarez@workpulse.com',
    phone: '+34 91 123 8899',
    manager: 'Avery Reed',
    startDate: 'Jan 15, 2020',
    attendance: '94%',
    productivity: '86',
  },
]
